# Week 2 / Day 2 — Daily Challenge  
## Gestion et analyse des données en Python

Dans ce défi quotidien, nous travaillons avec un dataset sur les salaires des emplois en science des données.  
L’objectif est de charger le dataset, normaliser la colonne du salaire avec la méthode Min-Max, appliquer une réduction de dimensionnalité avec PCA, puis regrouper les données par niveau d’expérience afin de calculer le salaire moyen et le salaire médian.

Ce travail permet de pratiquer trois étapes importantes en analyse de données : la préparation des données, la transformation des variables numériques et l’agrégation des informations pour produire des résultats interprétables.

In [9]:
import io
import pandas as pd
import numpy as np

from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.decomposition import PCA


df = pd.read_csv("/content/datascience_salaries.csv")
df = df.drop(columns=["Unnamed: 0"], errors="ignore")

df.head()

,job_title,job_type,experience_level,location,salary_currency,salary
0,Data scientist,Full Time,Senior,New York City,USD,149000
1,Data scientist,Full Time,Senior,Boston,USD,120000
2,Data scientist,Full Time,Senior,London,USD,68000
3,Data scientist,Full Time,Senior,Boston,USD,120000
4,Data scientist,Full Time,Senior,New York City,USD,149000

In [5]:
df.columns
df.info()
df.describe()
[col for col in df.columns if "salary" in col.lower()]

['salary_currency', 'salary']

## Normalisation Min-Max

La normalisation Min-Max permet de transformer les valeurs d’une colonne numérique dans une plage comprise entre 0 et 1.  
Dans cet exercice, la colonne `salary` a été normalisée afin de rendre les valeurs salariales comparables sur une même échelle.

La nouvelle colonne `salary_normalized` contient donc les salaires transformés entre 0 et 1.

In [12]:
minmax_scaler = MinMaxScaler()

df["salary_normalized"] = minmax_scaler.fit_transform(df[["salary"]])

df[["salary", "salary_normalized"]].head()

   salary  salary_normalized
0  149000           0.601010
1  120000           0.454545
2   68000           0.191919
3  120000           0.454545
4  149000           0.601010

In [ ]:
Z

## Réduction de dimensionnalité avec PCA

L’Analyse en Composantes Principales, ou PCA, permet de réduire le nombre de variables numériques tout en conservant une partie importante de l’information contenue dans le dataset.

Dans cet exercice, les colonnes numériques ont d’abord été standardisées, car PCA est sensible aux différences d’échelle entre les variables. Ensuite, PCA a été appliqué pour réduire les données à deux composantes principales : `PC1` et `PC2`.

Ces deux composantes permettent de représenter les données dans un espace plus simple, tout en conservant une partie de la variance du dataset.

In [13]:
numeric_df = df.select_dtypes(include=["int64", "float64"])

numeric_df.head()

   salary  salary_normalized
0  149000           0.601010
1  120000           0.454545
2   68000           0.191919
3  120000           0.454545
4  149000           0.601010

In [14]:
standard_scaler = StandardScaler()

numeric_scaled = standard_scaler.fit_transform(numeric_df)

numeric_scaled = pd.DataFrame(numeric_scaled, columns=numeric_df.columns)

numeric_scaled.head()

     salary  salary_normalized
0  2.586647           2.586647
1  1.695377           1.695377
2  0.097239           0.097239
3  1.695377           1.695377
4  2.586647           2.586647

In [15]:
pca = PCA(n_components=2)

pca_result = pca.fit_transform(numeric_scaled)

pca_df = pd.DataFrame(pca_result, columns=["PC1", "PC2"])

pca_df.head()

        PC1           PC2
0  3.658071 -2.556680e-16
1  2.397626 -4.087540e-17
2  0.137517  6.593929e-17
3  2.397626 -4.087540e-17
4  3.658071 -2.556680e-16

In [16]:
print("Variance expliquée par PC1 et PC2 :", pca.explained_variance_ratio_)
print("Variance totale conservée :", pca.explained_variance_ratio_.sum())

Variance expliquée par PC1 et PC2 : [1. 0.]
Variance totale conservée : 1.0

In [17]:
salary_by_experience = df.groupby("experience_level")["salary"].agg(
    salaire_moyen="mean",
    salaire_median="median"
).round(2)

salary_by_experience

                  salaire_moyen  salaire_median
experience_level
Entry                  36111.11         30000.0
Executive              76076.92         46000.0
Mid                    51786.89         51000.0
Senior                 75088.03         68000.0

## Conclusion

Dans cet exercice, le dataset des salaires en science des données a été chargé et exploré. La colonne `salary` a été normalisée avec la méthode Min-Max afin de ramener les valeurs entre 0 et 1. Ensuite, une réduction de dimensionnalité a été réalisée avec PCA pour représenter les colonnes numériques en deux composantes principales. Enfin, les données ont été regroupées par niveau d’expérience afin de calculer le salaire moyen et le salaire médian pour chaque groupe.